twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    paths:
      - '%kernel.project_dir%/templates'
      - '%kernel.project_dir%/vendor/knplabs/knp-menu-bundle/src/Resources/views'